**<u>THEORY PART AND INFO ABOUT PANDAS<u>**

Pandas is a free library that has important tools used in data analysis.

To use first we need to import it.

In [ ]:
import pandas as pd # imports the pandas library and assigns it the alias 'pd'

**Data frame**

Pandas provides 2 main classes for working with data:
1. Series: one dimensional labeled array
2. DataFrame: two dimensional table with rows and columns

We can create a DataFrame by passing a list of dictionaries where each one represent a row and the keys are the column name.

In [155]:
data = [{'ID': '001', 'Age': 68, 'Sex':'M', 'CT':2.543}, {'Age': 56, 'ID': '002', 'Sex': 'F', 'CT':2.34}, {'Age': 56, 'ID': '003', 'Sex': 'F', 'CT':2.41}]

print(data)
print(type(data))
print(data[0])
print(type(data[0]))

[{'ID': '001', 'Age': 68, 'Sex': 'M', 'CT': 2.543}, {'Age': 56, 'ID': '002', 'Sex': 'F', 'CT': 2.34}, {'Age': 56, 'ID': '003', 'Sex': 'F', 'CT': 2.41}]
<class 'list'>
{'ID': '001', 'Age': 68, 'Sex': 'M', 'CT': 2.543}
<class 'dict'>

In [ ]:
df = pd.DataFrame(data) # creates a DataFrame from the list of dictionaries 'data' and assigns it to the variable 'df'
print(df)

    ID  Age Sex     CT
0  001   68   M  2.543
1  002   56   F  2.340
2  003   56   F  2.410

This is a DataFrame where each row comes from the dictionary list and the column names are taken from the keys.

**Column data types**

Different columns can have different data types.

Usually numbers are stored as int or float and string are stored as objects dtype.

If needed you can convert an object to a string using .str().

In [ ]:
df.dtypes # shows the data types of each column in the DataFrame 'df'

ID         str
Age      int64
Sex        str
CT     float64
dtype: object

**View the data**

To analyze a DataFrame we can use .head() and .tail().

In [158]:
df.head(2) # shows the first 2 rows of the dataframe

    ID  Age Sex     CT
0  001   68   M  2.543
1  002   56   F  2.340

In [159]:
df.tail(1) # shows the last row of the dataframe

    ID  Age Sex    CT
2  003   56   F  2.41

We can use .columns() to see the columns names.

In [160]:
df.columns # shows the column names of the dataframe

Index(['ID', 'Age', 'Sex', 'CT'], dtype='str')

**Shape of the DataFrame**

Using .shape() we get a tuple representing the dimensions of the df

In [ ]:
df.shape # shows the number of rows and columns in the dataframe

(3, 4)

We can access a single column using df.ColumnName or df['ColumnName']

In [162]:
CT_dataset = df.CT # selects the 'CT' column from the dataframe and creates a new Series object called CT_dataset

print(CT_dataset) # prints the CT_dataset Series object
print(type(CT_dataset)) # prints the type of the CT_dataset object

0    2.543
1    2.340
2    2.410
Name: CT, dtype: float64
<class 'pandas.Series'>

**Summary statistics**

Using .describe() we get a statistical summary of the numerical columns in the df:
* Count
* Mean
* Std deviation
* Min and Max
* Quartiles (25%, 50%, 75%)

In [ ]:
df.describe() # provides summary statistics of the numerical columns in the dataframe

             Age        CT
count   3.000000  3.000000
mean   60.000000  2.431000
std     6.928203  0.103116
min    56.000000  2.340000
25%    56.000000  2.375000
50%    56.000000  2.410000
75%    62.000000  2.476500
max    68.000000  2.543000

**Selection**

We can select specific data from the df using labels or conditions.

Passing a column label (string) in brackets selects that column and returns a Series.

This is equivalent to using dot notation (df.Age), but bracket notation is preferred when column names have spaces or special characters.

In [164]:
df['Age'] # selects the 'Age' column from the dataframe

0    68
1    56
2    56
Name: Age, dtype: int64

For a df, using slicing syntax like [start:stop] selects rows by position, where stop is excluded.

In [ ]:
df[0:2] # selects the first 2 rows of the dataframe

    ID  Age Sex     CT
0  001   68   M  2.543
1  002   56   F  2.340

We can use .iloc[] to select rows and columns by their integer position.

In [166]:
df.iloc[2] # selects the first 2 rows of the dataframe using integer location-based indexing

ID      003
Age      56
Sex       F
CT     2.41
Name: 2, dtype: object

Integer slicing with .iloc[] behaves similarly to standard Python and NumPy slicing, we can use row and column indices to extract specific parts of the df.

In [167]:
df.iloc[2, 0:2] # selects the first 2 rows and columns 0:2 of the df

ID     003
Age     56
Name: 2, dtype: object

We can also pass lists of integer positions to .iloc[] to select multiple rows and columns.

In [168]:
df.iloc[[0,1], [0,2]] # selects the first 2 rows and columns 0 and 2 of the df

    ID Sex
0  001   M
1  002   F

And for slicing rows explicitly:

In [ ]:
df.iloc[0:2,:] # selects the first 2 rows and all columns of the df

    ID  Age Sex     CT
0  001   68   M  2.543
1  002   56   F  2.340

We can use : to slice rows explicitly and select all columns by including : in the column position.

In [170]:
df.iloc[:, 0:2] # selects all rows and columns 0:2 of the df

    ID  Age
0  001   68
1  002   56
2  003   56

To access a single value in the DataFrame by its row and column position:

In [171]:
df.iloc[0,0] # selects the value in the first row and first column of the df

'001'

**Missing data**

In pandas, missing data is typically represented using np.nan (Not a Number), which comes from NumPy.

Missing values are automatically excluded from most computations (like mean, sum, etc.).

**Dropping missing data**

Using DataFrame.dropna() removes any rows that contain at least one missing value.

* how = "any": drop rows if any column has a missing value
* inplace = True: perform the operation in place without returning a new DataFrame

In [172]:
import numpy as np
import pandas as pd

data1 = [{'ID': '001', 'Age': np.nan, 'Sex':'M', 'CT':2.543}, {'Age': 56, 'ID': '002', 'Sex': 'F', 'CT':2.34}, {'Age': 56, 'ID': '003', 'Sex': 'F', 'CT':2.41}]

print (type(data1)) # List of dictionaries
print (type(data1[0])) # Each element is a dictionary

df1 = pd.DataFrame(data1)
print (df1)

df2 = df1.dropna(how="any")
print (df2) # Only rows without NaN are kept
print (df1) # The original DataFrame remains unchanged

df1.dropna(how="any", inplace=True)
print(df1) # Now df1 has been updated: rows with NaN are removed

<class 'list'>
<class 'dict'>
    ID   Age Sex     CT
0  001   NaN   M  2.543
1  002  56.0   F  2.340
2  003  56.0   F  2.410
    ID   Age Sex    CT
1  002  56.0   F  2.34
2  003  56.0   F  2.41
    ID   Age Sex     CT
0  001   NaN   M  2.543
1  002  56.0   F  2.340
2  003  56.0   F  2.410
    ID   Age Sex    CT
1  002  56.0   F  2.34
2  003  56.0   F  2.41

**Stats**

By default, pandas excludes missing data (NaN) from statistical operations.

You can compute common statistics such as mean, sum, min, max, etc.

In [ ]:
df[['Age', 'CT']].mean() # calculates the mean of the 'Age' and 'CT' columns in the dataframe df

Age    60.000
CT      2.431
dtype: float64